# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27aea1a560eda4415cfdea2fd8b0733165efcc103cd9aadc43c4a8e0196799f99c0c761784bc4ca1e857147aea7da576abf7848f7f272a6f0796cf1acc71533a

test:
  secret_key_base: c2973242caf332bcfe98f07461879555d16dcd900b9615f08275e29d51c8e420ecaf2f254179538ea8d20cde18d97070c29a97a33610a144865ce298a785c5d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
